# Generated by Django 4.1.4 on 2022-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
